[alias]
build-sbf = "build --target bpfel-unknown-none --release"
test-sbf  = "test --target bpfel-unknown-none"

[target.bpfel-unknown-none]
rustflags = [
    "-C", "link-arg=-z",
    "-C", "link-arg=notext",
]
